version: '3.9'

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: semanticadb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d semanticadb"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: semanticadb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

  embed:
    build: ./embed
    ports:
    - "5001:5001"
    environment:
      PORT: 5001
      DB_HOST: db
      DB_PORT: 5432
      DB_URL: postgresql://user:password@db:5432/semanticadb
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
